spring.application.name=GuiaJuridicoBack

#CLEAN CONSOLE
logging.level.root=WARN
logging.level.com.seupacote=INFO
spring.main.banner-mode=off



spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/guia_juridico_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Lmsf2019!}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Chave secreta para assinatura dos tokens JWT
jwt.secret=${JWT_SECRET:Q2xhcmEtw6ktYS1tZWxob3ItcGVzc29hLWRvLW11bmRv}

# Habilita a inicialização preguiçosa para acelerar o startup
spring.main.lazy-initialization=true
server.port=${SERVER_PORT:8080}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
